language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
install:
  - phpenv config-rm xdebug.ini
  - ./build.sh install
script:
  - ./build.sh test
cache:
  directories:
    - $HOME/.composer/cache