language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
install:
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
  - composer install --prefer-dist -n --no-suggest
script:
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpspec run
  - vendor/bin/behat --profile default
cache:
  directories:
    - $HOME/.composer/cache
